### ISSUE TITLE
Saving the model 

### ISSUE THREAD

**Issue by Afef00** [Nano-Neuro-Research-Lab/Seizure-prediction-CNN#2]
I was wondering if I want to save the model sould I modify in CNN.py this line        

filepath="modell_%s_%s.h5" %(self.target, self.mode),
			verbose=0, save_best_only=True)
to this 
filepath="modell_%s_%s.h5" %(self.target, self.mode),
			verbose=0, save_best_only=True,save_weights_only=False)

**Comment by truongduynhan** [comment]
Both should work. The difference is that the former will save weights+model's topology while the latter will save weights only.

**Comment by Afef00** [comment]
You mean this will save the model +weights ? :
filepath="modell_%s_%s.h5" %(self.target, self.mode),
verbose=0, save_best_only=True)

Also one more thing in the evaluation of the model performance I wanted to calculate the model's accuracy instead of Auc using :
       from sklearn.metrics import accuracy_score
        accuracy_score(y, predictions)
        print('Test AC is:',accuracy_score)
However,I got this errror message **"TabError: inconsistent use of tabs and spaces in indentation"**

**Comment by truongduynhan** [comment]
You mean this will save the model +weights ? --> YES

The error you get is about python indentation. Make sure that you use consistent indentation (tab or space) throughout each .py file.

**Comment by Afef00** [comment]
Thanks !!
