### ISSUE TITLE
How do I get the sampling_CHBMIT.csv

### ISSUE THREAD

**Issue by Zhaojqq** [Nano-Neuro-Research-Lab/Seizure-prediction-CNN#4]
Hello, what is the meaning of the 'ictal_ovl' in in the sampling_CHBMIT.csv and how is the ' ictal_ovl' calculated?
I'm Looking forward to your reply.

**Comment by lsw9803** [comment]
Had the same question too. Have you got the answer？

**Comment by truongduynhan** [comment]
Hi @Zhaojqq and @Isw9803,

Ictal_ovl is the percentage of non-overlapping when oversampling preictal samples to remedy the un-balance of the dataset. Initially, they are all set to 1 (no oversampling of preictal). Then ictal_ovl is calculated based on the ratio of preictal vs interictal samples. I should have got a better name for "Ictal_ovl".

**Comment by rajatanand86** [comment]
Hello.
Can you please help with this. Say for chb20 in CHBMIT folder, i run the code first with ictal_ovl=1 in sampling_CHBMIT.csv, get the hickle files: ictal_20.hickle and interictal_20.hickle. Get the total samples in these two files, say ictal_20[0].shape=(435, 1, 22, 55, 114) and len(ictal_20)=5, then samples=435*5 and so on and then calculate the ratio ? and then run the code again after deleting the hickle files and after updating the csv with this new ratio?
