### ISSUE TITLE
Meaning of values in CHBMIT csv files

### ISSUE THREAD

**Issue by sourav1312** [Nano-Neuro-Research-Lab/Seizure-prediction-CNN#6]
Hello!

Could you please explain how the **segmentation.csv** and **special_interictal.csv** files were generated in the **CHBMIT subfolder**? The numeric values associated with the above files are quite confusing. It would be very helpful if a suitable explanation is provided.

Thanks and regards,
Sourav

**Comment by CageChen** [comment]
@notbadday I have the same question, could you please explain the meaning of each column in these files? Thanks a lot!

**Comment by AsmaBalamash** [comment]
I have the same question, kindly provide us with detail explanation for these values.

**Comment by truongduynhan** [comment]
Added an explanation for those values as a readme in the CHBMIT folder.
