### ISSUE TITLE
Mind if I pick your brains for a minute? 

### ISSUE THREAD

**Issue by YANKT** [Nano-Neuro-Research-Lab/Seizure-prediction-CNN#8]
Hi buddy.Thank you for the open source code.Mind if I pick your brains for a minute? I want to debug your code, but I only want to debug of the CHB-MIT dataset. How do I block out parts of Kaggle and FB

**Comment by Morilla123** [comment]
Sorry for answering you, I wasn't paying attention to github. Yes of course I can help you. What do you need punctually and specifically and I try to do it

**Comment by YANKT** [comment]
> 很抱歉回答你，我没有关注github。是的，我当然可以帮助你。你需要什么准时和具体的，我试着去做

Thanks for your reply, I do need some help.Can we private chat？ 
My mail:ykttt@hotmail.com.
